### ISSUE TITLE
Running "finish" fails

### ISSUE THREAD

**Issue by 63990** [ACRC/oci-cluster-terraform#24]
I'm using an older version of CitC (initially forked ~6 months ago, but keep up to date until 15th March 2019) and a forked ansible script (last updated 15th March 2019).

Using this configuration, I get the following error when I run 'finish'
```
[opc@mgmt ~]$ ./finish  
ERROR! the playbook: finalise.yml could not be found 

############################################# 
Error: Ansible run did not complete correctly 
############################################# 
```

I tried running a fresh pull (so using the default playbook too) and now get the error
```
[opc@mgmt ~]$ ./finish  
Error: Could not find limits.yaml 
Please create the file and rerun this script. 
```

**Comment by milliams** [comment]
I'm closing this in preference of milliams/cluster-in-the-cloud#3
