### ISSUE TITLE
Dictionary in network.tf

### ISSUE THREAD

**Issue by tethig** [ACRC/oci-cluster-terraform#39]
Hi,
I have terraform v0.12.5 and `terraform init` threw an error. The fix (suggested by `terraform validate`) is super simple, add an equals in line 53 of network.tf (to give `tcp_options = {`). However, I haven't tested if that's compatible with previous versions of terraform.
thanks very much for your work,
Ben

**Comment by milliams** [comment]
We currently only support Terraform 0.11 but are planning up updating to 0.12 very soon. We've got a big change with support or GCP incoming but after that we can look at updating to 0.12.

**Comment by tethig** [comment]
Hi, Thanks very much for your response. That's great. I will actually persist a little with mods on my cloned repo (the 0.12upgrade script seems to take care of what I thought was the thorniest issue) and let you know if I get it working. Failing that I will roll back Terraform to 0.11. many thanks again! Ben

**Comment by tethig** [comment]
I'm happy to report that when I got all my (user-specific) ducks in a row the current version is effectively fixed by terraform by `terraform 0.12upgrade`. The update script fixes variable declarations and formatting of blocks. This is better than using the validate function.
