### ISSUE TITLE
Incomplete setup

### ISSUE THREAD

**Issue by tethig** [ACRC/oci-cluster-terraform#40]
Hi, I hope I'm not missing anything, but I can't seem to complete setup for new clusters. To make a reproducible example I've used Terraform v0.11.15-oci to initiate a cluster on the Oracle cloud. Unfortunately the finish script reports that mgmt has not completed setup (even after ~24 hours). Reading ansible-pull.log from my latest iteration it reports an error as follows:

```
Starting Ansible Pull at 2019-08-27 20:44:24
/usr/bin/ansible-pull --url=https://github.com/ACRC/slurm-ansible-playbook.git --checkout=3 --invent
ory=/root/hosts management.yml
 [WARNING]: Could not match supplied host pattern, ignoring: mgmt
 [WARNING]: Your git version is too old to fully support the depth argument.
Falling back to full checkouts.
mgmt.subnet.clustervcn.oraclevcn.com | CHANGED => {
    "after": "4aa832749d3e79961587713b4a1950baead67127",
    "before": null,
    "changed": true
}
 [WARNING]: Could not match supplied host pattern, ignoring: mgmt
```

I can't quite relate this to other issues and I cannot quite see the error in my terraform.tfvars file which ends:
```
ManagementShape = "VM.Standard2.1"
ManagementAD = "2"
FilesystemAD = "2"

```
Any advice would be very much appreciated and I'll be happy to supply any more information. many thanks

**Comment by milliams** [comment]
This is indeed a problem. It seems that the RPM provided by RedHat has changed and the path to Python has also changed from `/bin/python63` to just `/bin/python3`. I've got a fix which should be merged soon. I'll update this issue once it's resolved.
